export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'

export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'

export const REGISTER_USER_VIA_LOGIN_MODAL = 'REGISTER_USER_VIA_LOGIN_MODAL'
export const REGISTER_USER_VIA_LOGIN_MODAL_SUCCESS = 'REGISTER_USER_VIA_LOGIN_MODAL_SUCCESS'
export const REGISTER_USER_VIA_LOGIN_MODAL_FAILURE = 'REGISTER_USER_VIA_LOGIN_MODAL_FAILURE'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'
export const USER_RESET = 'USER_RESET'